//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int ID { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Adddate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
