//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicMenu
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string MenuLink { get; set; }
        public Nullable<int> MneuLevel { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string MenuStr { get; set; }
        public string CSSClass { get; set; }
        public Nullable<System.DateTime> Adddate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
