//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductVarients = new HashSet<ProductVarient>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> LocalShipingCharge { get; set; }
        public Nullable<decimal> ZonalShipingCharge { get; set; }
        public Nullable<decimal> NationalShippingCharge { get; set; }
        public Nullable<int> StockCount { get; set; }
        public Nullable<System.DateTime> MgfDate { get; set; }
        public string MgfDetail { get; set; }
        public string ShellLife { get; set; }
        public string ProductWarning { get; set; }
        public string Description { get; set; }
        public string EstimateDeliveryTime { get; set; }
        public string MainImage { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Image6 { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> MiniCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string InactiveReason { get; set; }
        public Nullable<bool> ApprovedByAdmin { get; set; }
        public Nullable<bool> IsReturnable { get; set; }
        public int ReturnDays { get; set; }
        public string productCode { get; set; }
        public Nullable<bool> paymentModeCash { get; set; }
        public Nullable<bool> paymentModeBank { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual MiniCategory MiniCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVarient> ProductVarients { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
