//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> VarientId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public decimal Rating1 { get; set; }
        public string Reviews { get; set; }
        public Nullable<System.DateTime> Adddate { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
