//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrderDetail
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductVarientId { get; set; }
        public Nullable<int> TempOrderID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<bool> IsUserWishList { get; set; }
    
        public virtual TempOrder TempOrder { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
