//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBusinessDetail
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirmName { get; set; }
        public string GSTIN { get; set; }
        public string FullAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PanNo { get; set; }
        public string AddressProofImg { get; set; }
        public Nullable<System.DateTime> IsActive { get; set; }
        public Nullable<System.DateTime> IsDelete { get; set; }
        public Nullable<System.DateTime> AddUpdate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string PIN { get; set; }
        public string Signature { get; set; }
        public string Logo { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
